#配置运行端口号
server:
  port: 8083
##配置应用名称
spring:
  application:
    name: application-client
  redis:
    host: 192.168.0.110
#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#hystrix服务降级
hystrix:
  command:
    default:
      execution:
        timeout:
          # 如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为容错根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000 # 超时时间，默认1000ms
