server:
  port: 9002
spring:
  application:
    name: lcn-course-manager
  data:
    mongodb:
      host: 192.168.0.110
      port: 27017
      username: root
      password: root
      database: lcn
      authentication-database: admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.110:3306/tx-manager?serverTimezone=GMT@2B8
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070