server:
  port: 9001
spring:
  application:
    name: lcn-student-manager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.110:3306/lcn-student?serverTimezone=GMT%2B8
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070